//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL
{
    public partial class Equipement
    {
        #region Primitive Properties
    
        public virtual int idEquipement
        {
            get;
            set;
        }
    
        public virtual int idAdmin
        {
            get { return _idAdmin; }
            set
            {
                if (_idAdmin != value)
                {
                    if (Administration != null && Administration.idAdmin != value)
                    {
                        Administration = null;
                    }
                    _idAdmin = value;
                }
            }
        }
        private int _idAdmin;
    
        public virtual int idSprv
        {
            get { return _idSprv; }
            set
            {
                if (_idSprv != value)
                {
                    if (Superviseur != null && Superviseur.idSprv != value)
                    {
                        Superviseur = null;
                    }
                    _idSprv = value;
                }
            }
        }
        private int _idSprv;
    
        public virtual string localeEquipement
        {
            get;
            set;
        }
    
        public virtual string adresseIPEquipement
        {
            get;
            set;
        }
    
        public virtual string nomEquipement
        {
            get;
            set;
        }
    
        public virtual string descriptionEquipement
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> modeEquipement
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Administration Administration
        {
            get { return _administration; }
            set
            {
                if (!ReferenceEquals(_administration, value))
                {
                    var previousValue = _administration;
                    _administration = value;
                    FixupAdministration(previousValue);
                }
            }
        }
        private Administration _administration;
    
        public virtual Superviseur Superviseur
        {
            get { return _superviseur; }
            set
            {
                if (!ReferenceEquals(_superviseur, value))
                {
                    var previousValue = _superviseur;
                    _superviseur = value;
                    FixupSuperviseur(previousValue);
                }
            }
        }
        private Superviseur _superviseur;

        #endregion
        #region Association Fixup
    
        private void FixupAdministration(Administration previousValue)
        {
            if (previousValue != null && previousValue.Equipements.Contains(this))
            {
                previousValue.Equipements.Remove(this);
            }
    
            if (Administration != null)
            {
                if (!Administration.Equipements.Contains(this))
                {
                    Administration.Equipements.Add(this);
                }
                if (idAdmin != Administration.idAdmin)
                {
                    idAdmin = Administration.idAdmin;
                }
            }
        }
    
        private void FixupSuperviseur(Superviseur previousValue)
        {
            if (previousValue != null && previousValue.Equipements.Contains(this))
            {
                previousValue.Equipements.Remove(this);
            }
    
            if (Superviseur != null)
            {
                if (!Superviseur.Equipements.Contains(this))
                {
                    Superviseur.Equipements.Add(this);
                }
                if (idSprv != Superviseur.idSprv)
                {
                    idSprv = Superviseur.idSprv;
                }
            }
        }

        #endregion
    }
}
