//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace DAL
{
    public partial class UserDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=UserDBEntities";
        public const string ContainerName = "UserDBEntities";
    
        #region Constructors
    
        public UserDBEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public UserDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public UserDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Administration> Administrations
        {
            get { return _administrations  ?? (_administrations = CreateObjectSet<Administration>("Administrations")); }
        }
        private ObjectSet<Administration> _administrations;
    
        public ObjectSet<Equipement> Equipements
        {
            get { return _equipements  ?? (_equipements = CreateObjectSet<Equipement>("Equipements")); }
        }
        private ObjectSet<Equipement> _equipements;
    
        public ObjectSet<Site> Sites
        {
            get { return _sites  ?? (_sites = CreateObjectSet<Site>("Sites")); }
        }
        private ObjectSet<Site> _sites;
    
        public ObjectSet<Superviseur> Superviseurs
        {
            get { return _superviseurs  ?? (_superviseurs = CreateObjectSet<Superviseur>("Superviseurs")); }
        }
        private ObjectSet<Superviseur> _superviseurs;

        #endregion
    }
}
