//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DAL
{
    public partial class Site
    {
        #region Primitive Properties
    
        public virtual int idSite
        {
            get;
            set;
        }
    
        public virtual int idAdmin
        {
            get { return _idAdmin; }
            set
            {
                if (_idAdmin != value)
                {
                    if (Administration != null && Administration.idAdmin != value)
                    {
                        Administration = null;
                    }
                    _idAdmin = value;
                }
            }
        }
        private int _idAdmin;
    
        public virtual string localeSite
        {
            get;
            set;
        }
    
        public virtual string descriptionSite
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> modeSite
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Administration Administration
        {
            get { return _administration; }
            set
            {
                if (!ReferenceEquals(_administration, value))
                {
                    var previousValue = _administration;
                    _administration = value;
                    FixupAdministration(previousValue);
                }
            }
        }
        private Administration _administration;

        #endregion
        #region Association Fixup
    
        private void FixupAdministration(Administration previousValue)
        {
            if (previousValue != null && previousValue.Sites.Contains(this))
            {
                previousValue.Sites.Remove(this);
            }
    
            if (Administration != null)
            {
                if (!Administration.Sites.Contains(this))
                {
                    Administration.Sites.Add(this);
                }
                if (idAdmin != Administration.idAdmin)
                {
                    idAdmin = Administration.idAdmin;
                }
            }
        }

        #endregion
    }
}
